### ISSUE TITLE
Feature Request: Make it Easy to Customize with JSON Files

### ISSUE THREAD

**Issue by codewithtyler** [DulangaDasanayake/dulangadasanayake.github.io#1]
Hey DulangaDasanayake! Just wanted to say I checked out your portfolio, and it looks awesome! Was wondering if you'd be up for making it more plug-and-play so folks like me could use it too. Like, maybe set it up so we can just edit some JSON files to add our own projects and skills without messing with all the code? I know I’d get a ton of use out of that, and I bet others would too! Anyway, thanks for sharing your work, and for even thinking about this!

**Comment by DulangaDasanayake** [comment]
Hey there! Thanks for checking out my portfolio and for the kind words! I love the idea of making it more plug-and-play, but I don’t currently have the time to implement that due to my work hours. However, if you or your friends want to contribute to make this more plug-and-play, I’d be happy to add you as contributors! Your feedback means a lot, and I appreciate your interest in helping out!

**Comment by codewithtyler** [comment]
Sure I can see about doing that. I did see that you sent me an invitation to work on it but when I went to accept it seems that the invitation was removed.
